services:
  - type: web_service
    name: line-webhook
    env: node
    branch: main
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: CHANNEL_ACCESS_TOKEN
        value: ""
